apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      containers:
      - name: sales-service
        image: sales-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          value: "postgresql://k8s_user:k8s_password@host.docker.internal:5432/sales_db"
        - name: PYTHONPATH
          value: "/app"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: dev
spec:
  selector:
    app: sales-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP