version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-service:
    build: ./services/orders
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/orders_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  sales-service:
    build: ./services/sales
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/sales_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
